services:
  - type: web
    name: leaderboard-backend
    runtime: go
    plan: free
    buildCommand: go build -o main main.go
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
